[[core-prereqs-db]]
= Database backend

{productname} stores most of its configuration and all metadata and by default also audit logs inside its database backend. PostgreSQL and MySQL are supported but PostgreSQL is the preferred database backend since it can be used for both Quay and Clair.

[NOTE]
====
Since the {productname} 3.6 release, using MySQL/MariaDB as the database backend for {productname} is deprecated and support will eventually be removed. Until then, MySQL is still supported as per the link:https://access.redhat.com/articles/4067991[support matrix] but will not receive additional features or explicit testing coverage.
====

The Red Hat Quay Operator only supports PostgreSQL as a managed database since {productname} 3.4. 
External MySQL/MariaDB databases can still be leveraged using a custom deployment configuration (unmanaged/external database) until support is removed.

Deploying {productname} in a highly available (HA) configuration requires that your database is provisioned for high availablity. 
If {productname} is running on public cloud infrastructure, it is recommended that you use multi-zone deployments with at least one read-only replica. 
If {productname} is deployed on-premise an availability concept is needed that makes the database resilient against server or even datacenter failures. 
For protection against entire data center outages the database should rely on log-shipping or similar data replication approaches.

{productname} ships with a single-instance PostgreSQL database based on the Red Hat Software Collections project. 
When deployed via the {productname} operator on OpenShift the database will be subject to Kubernetes failing over the database pod in case of a node failure and provides high-availability based on automatic restart. 
For VM-based deployments additional software (for example quorum-based clustering software like the Red Hat Enterprise Linux High-Availability Add-on) and services need to be provided by the user to achieve high availability via failover across nodes for the database aligned with the recommendations above.

Geo-replication requires a single, shared database that is accessible from all regions. 
Such a database should have a failover concept across regions for the purposes of disaster recovery. 
This requires  additional software and services provided by the user.